spring:
  mongodb:
    uri: mongodb+srv://kunaljha5002:12345@cluster0.ybaptf4.mongodb.net/journaldb?retryWrites=true&w=majority

logging:
  level:
    org.springframework.boot.autoconfigure.mongo: DEBUG
    org.springframework.data.mongodb: DEBUG
